[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Docugami <contact@docugami.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.22"}
langchain = "^0.0.345"
openai = "^0.28.1"
tiktoken = ">=0.5.1"
lxml = "^4.9.3"
dgml-utils = "^0.2.0"
docugami-kg-rag = {path = "packages/docugami-kg-rag", develop = true}
typer = "^0.9.0"
docugami = "^0.0.8"
black = "^23.11.0"
pandas = "^2.1.3"
pyright = "^1.1.338"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"
ipykernel = "*"
black = "*"
pytest = "*"
pyyaml = "*"
ruff = "*"

[tool.black]
line-length = 127

[tool.ruff]
ignore = ["E501"]

[tool.langserve]
export_module = "docugami_kg_rag"
export_attr = "chain"

[tool.poetry.scripts]
index = "packages.docugami-kg-rag.index:main"

[tool.pytest.ini_options]
addopts = "--doctest-modules"
norecursedirs = ".venv"

[tool.pyright]
ignore = ["**/node_modules", "**/__pycache__", ".venv"]
reportMissingImports = true
reportMissingTypeStubs = false

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
